name: orre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  android_intent_plus: ^4.0.3
  animated_flip_counter: ^0.3.4
  cached_network_image: ^3.3.1
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter:
    sdk: flutter
  flutter_naver_map: ^1.1.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  flutter_test:
    sdk: flutter
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  live_activities: ^1.9.1+1
  mockito: ^5.4.4
  nfc_manager: ^3.4.0
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.4
  sliver_app_bar_builder: ^1.1.0
  sqflite: ^2.3.3
  stomp_dart_client: ^1.0.3
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets: 
    - assets/images/orre_logo.png