name: orre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
