name: orre
description: "Smart Consumer Life with OrRe"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  another_flutter_splash_screen: ^1.2.0
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5
  firebase_analytics: ^10.10.5
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+1
  flutter_naver_map: ^1.1.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.1
  flutter_secure_storage: ^9.0.0
  flutter_test:
    sdk: flutter
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  get: ^4.6.6
  go_router: ^14.1.3
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  internet_connectivity_checker: ^1.0.2
  live_activities: ^1.9.1+1
  loader_overlay: ^4.0.0
  mockito: ^5.4.4
  nfc_manager: ^3.4.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.3
  sliver_app_bar_builder: ^1.1.0
  sqflite: ^2.3.3
  stomp_dart_client: ^1.0.3
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets: 
    - assets/images/orre_logo.png
    - assets/images/loading_orre.gif
    - assets/images/waveform/wave_shadow.png
    - assets/images/waveform/wave.png

  fonts :
    - family: Dovemayo_gothic
      fonts :
        - asset : assets/fonts/Dovemayo_gothic.ttf